name: Report a bug
description: Stumbled across a bug? report it here.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug with Crossbow Enchants!
  - type: textarea
    attributes:
      label: What happened?
      description: Make sure to write down important details.
      placeholder: Describe the issue you encountered...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Versions
  - type: input
    attributes:
      label: Crossbow Enchants Version
      description: What version of Crossbow Enchants were you using?
      placeholder: e.g., 1.x.x
    validations:
      required: true
  - type: input
    attributes:
      label: Fabric API Version
      description: What version of Fabric API were you using?
      placeholder: e.g., 0.10x.x
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you using?
      options:
        - 1.21.1
        - 1.21
        - 1.20.6
        - 1.20.5
        - 1.20.4
        - 1.20.3
        - 1.20.2
        - 1.20.1
        - 1.20
        - Other
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional Information
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Relevant logs...
      render: shell
  - type: textarea
    attributes:
      label: Other Mods
      description: If you can, please supply a list of installed Mods (besides Crossbow Enchants and Fabric API).
      placeholder: List other mods you have installed...
      render: shell
  - type: markdown
    attributes:
      value: |
        Thank you for helping me improve Crossbow Enchants!
